Добавил в postinst запрос email у пользователя, для замены по шаблону в файле конфигурации easy-rsa vars, а также добавил команды в файл генерации запроса на подпись

diff --git a/client-0.1/debian/postinst b/client-0.1/debian/postinst
--- a/client-0.1/debian/postinst
+++ b/client-0.1/debian/postinst
@@ -45,7 +45,21 @@ case "$1" in
             exit 1
         fi
 
-        # create PKI (secret key & CA)
+        # configure file vars
+        if [ -f $PATHEASYRSAVARS ]; then
+            read "Enter your email: " EMAIL
+            if [ ! -z $EMAIL ]; then
+                sed -i "s|EXPHOSTNAME|$EMAIL|g" $PATHEASYRSAVARS
+            else
+                echo "Error: not specified email - break!"
+                exit 1
+            fi
+        else
+            echo "Error: config template not exist - break!"
+            exit 1
+        fi
+
+        # create PKI
         cd $PATHEASYRSAUSR
         # init PKI
         ./easyrsa init-pki
