Добавил код по конфигурации easy-rsa в маинтейнерские скрипты, а дакже установку пользовательских скриптов в install пакета

diff --git a/client-0.1/debian/postinst b/client-0.1/debian/postinst
--- a/client-0.1/debian/postinst
+++ b/client-0.1/debian/postinst
@@ -17,9 +17,47 @@ set -e
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+PATHEASYRSADEF="/usr/share/easy-rsa"
+PATHEASYRSAUSR="/opt/easy-rsa"
+PATHEASYRSACA="${PATHEASYRSAUSR}/pki/ca.crt"
+PATHEASYRSAVARS="${PATHEASYRSAUSR}/vars"
+PATHUSRSCRIPTS="/urs/bin"
 
 case "$1" in
     configure)
+
+        # create symlink in user folder
+        if [ -d $PATHEASYRSAUSR ]; then
+            if [ -d $PATHEASYRSADEF ]; then
+                ln -s /usr/share/easy-rsa/* ${PATHEASYRSAUSR}
+                read "Enter your user login: " LOGIN
+                if [ ! -z $LOGIN ]; then
+                    chown -R $LOGIN:$LOGIN ${PATHEASYRSAUSR}
+                else
+                    echo "WARNING: user login not specified, failed to change owner and group for ${PATHEASYRSAUSR}, there may be access problems!"
+                fi
+            else
+                echo "Error: not exist folder ${PATHEASYRSADEF}, break install!"
+                exit 1
+            fi
+        else
+            echo "Error: not exist folder ${PATHEASYRSAUSR}, break install!"
+            exit 1
+        fi
+
+        # create PKI (secret key & CA)
+        cd $PATHEASYRSAUSR
+        # init PKI
+        ./easyrsa init-pki
+        # create key Diffi-Hellman
+        ./easyrsa gen-dh
+
+        # add exec mode scripts
+        chmod +x ${PATHUSRSCRIPTS}/client_gen_req.sh && chmod +x ${PATHUSRSCRIPTS}/client_gen_ovpn.sh
+
+        echo "Installation completed. Start creating a certificate issue request with the command: "
+        echo "$ ${PATHUSRSCRIPTS}/client_gen_req.sh"
+        echo "And follow further instructions..."
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
